kind: ENC[AES256_GCM,data:nRUP5ohv,iv:OiFJlWfzpnKBYg3IWkIjC6nY9ZRn5Z5EkJJ2rfvJtBg=,tag:ZMkMq58A38dh8IyqfeWePQ==,type:str]
ansible_user: ENC[AES256_GCM,data:11VViA==,iv:XpMs9S+lnVIoig9cC8CEmEFiTrl6dayabTyZ11TwQpQ=,tag:NAj3lOuel8+gtOrP7L8lXw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WCsdWYo=,iv:BCnRSgxUBe6lK3DrKmybq73C0ccXqZZgqhZlib/7WFU=,tag:589PWDJRRo6t7K9/1sP6Ew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdE1ndGNNeGJrOXdyYXBL
            L2paaUMrVnVPZ1hjc21SM0c5cytpUXRUdjM4Ck5FeHhHOWNvYnNOeUIyUXlwSWl1
            cmU0QnpPcTR0K2VwSWpxWmN4YXNXSUEKLS0tIFNEaE5lTWtDVkpZd1dYWE5xVzB2
            YmRzYlNrNDNHK20xT3hLSEVVTHk1a1UKXkwa6JFrbQyzQ/lhdRVSzgsBuI3s8s/x
            Tlx0FIM8spGWPvFcRK6+D7Y4w3elF4V6TblhnJdxBAH5wDsd/tYCCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T17:59:48Z"
    mac: ENC[AES256_GCM,data:+Rdblqru47TbIy1zOKGRCGfFDQWV0A5nHiUmnrD6BSFtUKzQn0cA5ydjV/FtTC4+qZN21cI8zKC/VrRIMdYRNdEQOElkBbzj+ft5TkwPtTLgZhL9PxgM80Gg7n5/U6P3GM62btvwMSUuX5RriMr4Xkdn69lDnXwAClGbsAeUamI=,iv:giGBGBxsk+nmNzg0Swc5c7E48MEoSadOSlxP0GIx07E=,tag:Kdu4fG6vs9w1gp0Fid5i/w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
