---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-v14
  namespace: default
spec:
  # daily, 4am UCT
  schedule: "0 0 4 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-v14
