---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis
  namespace: default
spec:
  # refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: redis-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        redis-password: "{{ .REDIS_PW }}"
  dataFrom:
    - extract:
        key: redis
