---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openproject
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: openproject-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        # OPENPROJECT_DB_PASSWORD: "{{ .OP_POSTGRES_PASS }}"
        # DATABASE_HOST: postgres-v16-rw.database.svc.cluster.local
        # DATABASE_PORT: 5432
        # DATABASE_URL: "postgres://openproject:{{ .OP_POSTGRES_PASS }}@postgres-v16-rw.database.svc.cluster.local/openproject"
        # Postgres
        password: "{{ .OP_POSTGRES_PASS }}"
        postgres-password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: openproject
    - extract:
        key: postgres
