---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openproject
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: openproject-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        OPENPROJECT_DB_USER_PASSWORD: "{{ .OPENPROJECT_DB_USER_PASSWORD }}"
        OPENPROJECT_DB_URL: |-
          postgres://{{ .OPENPROJECT_DB_USER }}:{{ .OPENPROJECT_DB_USER_PASSWORD }}@postgres-v16-rw.database.svc.cluster.local/openproject
        OPENPROJECT_SEED__ADMIN__USER__NAME: "{{ .OPENPROJECT_ADMIN_USER_NAME }}"
        OPENPROJECT_SEED__ADMIN__USER__PASSWORD: "{{ .OPENPROJECT_ADMIN_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: openproject
        INIT_POSTGRES_HOST: postgres-v16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .OPENPROJECT_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .OPENPROJECT_DB_USER_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: openproject
    - extract:
        key: postgres
