---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openproject
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      openproject:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: openproject-secret

          rails-migrate:
            dependsOn: init-db
            image: &image
              repository: docker.io/openproject/openproject
              tag: 14-slim@sha256:d104d60082a78282ea0d586fc1131f2d4fa737b008b7403fa7c4eead97391708
            envFrom: *envFrom
            command:
              - bin/rails
            args:
              - "db:migrate"
              - "RAILS_ENV=production"

        containers:
          app:
            image: *image
            env:
              OPENPROJECT_HOST__NAME: &host "projects.${SECRET_DOMAIN}"
              OPENPROJECT_CACHE__MEMCACHE__SERVER: openproject-memcached.default.svc.cluster.local:11211
              OPENPROJECT_RAILS__CACHE__STORE: memcache
              # POSTGRES_STATEMENT_TIMEOUT: 120
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            # resources:
            #   requests:
            #     cpu: 250m
            #     memory: 512Mi
            #   limits:
            #     memory: 4Gi

    service:
      app:
        controller: openproject
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          hajimari.io/group: "Apps"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Todo"
          gethomepage.dev/description: "OpenProject"
          gethomepage.dev/group: "Apps"
          gethomepage.dev/icon: "openproject.svg"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /var/openproject
      config:
        type: configMap
        name: openproject-configmap
        globalMounts:
          - path: /app/app/models/enterprise_token.rb
            subPath: enterprise_token.rb
            readOnly: true
