---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openproject
spec:
  interval: 30m
  chart:
    spec:
      chart: openproject
      version: 7.2.0
      sourceRef:
        kind: HelmRepository
        name: openproject
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    # openproject:
    #   envFrom:
    #     - secretRef:
    #         name: openproject-secret

    postgresql:
      bundled: false
      connection:
        host: postgres-v16-rw.database.svc.cluster.local
        port: 5432
      auth:
        existingSecret: openproject-secret
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "password"

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/group: "Apps"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Todo"
        gethomepage.dev/description: "OpenProject"
        gethomepage.dev/group: "Apps"
        gethomepage.dev/icon: "openproject.svg"
      host: projects.${SECRET_DOMAIN}
      # hosts:
      #   - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
      #     paths:
      #       - path: /
      #         pathType: Prefix
      #         service:
      #           name: main
      #           port: http

    persistence:
      enabled: true
      storageClassName: ceph-filesystem
