---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  # - ../../../../templates/volsync
configMapGenerator:
  - name: openproject-enterprise-crack
    files:
      - enterprise_token.rb=./enterprise_token-crack.rb
configurations:
  - kustomizeconfig.yaml
