---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configurations:
  - kustomize-config.yaml
configMapGenerator:
  - name: kps-generic-values
    files:
      - values.yaml=generic-values.yaml
  - name: kps-prometheus-values
    files:
      - values.yaml=prometheus-values.yaml
  - name: kps-alertmanager-values
    files:
      - values.yaml=alertmanager-values.yaml
