---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octoprint-data-v2
  namespace: printing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
