---
session:
  redis:
    high_availability:
      sentinel_name: redis-master
      nodes:
        - host: redis-node-0.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-1.redis-headless.database.svc.cluster.local
          port: 26379
        - host: redis-node-2.redis-headless.database.svc.cluster.local
          port: 26379

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules:
    - domain: ["jellyfin.${AUTHELIA_SESSION_DOMAIN}"]
      resources: ["^/metrics.*$"]
      policy: deny
    - domain: ["letsblockit.${AUTHELIA_SESSION_DOMAIN}"]
      resources: ["^/lists.*$"]
      policy: bypass
    - domain: ["navidrome.${AUTHELIA_SESSION_DOMAIN}"]
      resources: ["^/ping.*$", "^/rest.*$"]
      policy: bypass
    - domain: ["navidrome.${AUTHELIA_SESSION_DOMAIN}"]
      resources: ["^/metrics.*$"]
      policy: deny
    - domain: ["invite.${AUTHELIA_SESSION_DOMAIN}"]
      resources: ["^/join(/.*)?$", "^/j(/.*)?$", "^/setup(/.*)?$", "^/static(/.*)?$"]
      policy: bypass

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: grafana
        description: Grafana
        secret: "${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        redirect_uris: ["https://grafana.${AUTHELIA_SESSION_DOMAIN}/login/generic_oauth"]
        scopes: ["openid", "profile", "groups", "email"]
        userinfo_signing_algorithm: none
        pre_configured_consent_duration: 1y
      - id: bookstack
        description: Bookstack
        secret: "${BOOKSTACK_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: one_factor
        redirect_uris: ["https://bookstack.${AUTHELIA_SESSION_DOMAIN}/oidc/callback"]
        scopes: ["openid", "profile", "email"]
        userinfo_signing_algorithm: none
        pre_configured_consent_duration: 1h
