---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: node-red-backup
  namespace: default
spec:
  sourcePVC: node-red-data
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: node-red-restic-secret
    cacheCapacity: 5Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: node-red-restore
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: node-red-restic-secret
    destinationPVC: node-red-data
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 5Gi
    cacheStorageClassName: local-path
    storageClassName: ceph-block
