---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app autobrr
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/apps/media/autobrr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: autobrr
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 5m
