---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps
      darkTheme: espresso
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: true
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      namespaceSelector:
        matchNames:
          - default
          - home-automation
          - printing
          - media
          - monitoring
          - rook-ceph
          - flux-system
          - kube-system
          - database
          - networking
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "www.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    # podAnnotations:
    #   configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    # resources:
    #   requests:
    #     cpu: 15m
    #     memory: 64M
    #   limits:
    #     cpu: 15m
    #     memory: 64M
