---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: autobrr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        AUTOBRR__DATABASETYPE: postgres
        AUTOBRR__POSTGRESDATABASE: &dbName autobrr
        AUTOBRR__POSTGRESHOST: &dbHost postgres-v15-rw.database.svc.cluster.local
        AUTOBRR__POSTGRESUSER: &dbUser "{{ .AUTOBRR__POSTGRESUSER }}"
        AUTOBRR__POSTGRESPASS: &dbPass "{{ .AUTOBRR__POSTGRESPASS }}"
        AUTOBRR__POSTGRESPORT: "5432"
        AUTOBRR__SESSIONSECRET: "{{ .AUTOBRR__SESSIONSECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: autobrr
    - extract:
        key: postgres
