---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: grafana-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        GF_DATABASE_NAME: &dbName "{{ .GF_DATABASE_NAME }}"
        GF_DATABASE_HOST: postgres-v16-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: &dbUser "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: &dbPass "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        # GF_AUTH_GENERIC_OAUTH_API_URL: "{{ .GF_AUTH_GENERIC_OAUTH_API_URL }}"
        # GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{{ .GF_AUTH_GENERIC_OAUTH_AUTH_URL }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ .GF_AUTH_GENERIC_OAUTH_CLIENT_ID }}"
        # GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{{ .GF_AUTH_GENERIC_OAUTH_TOKEN_URL }}"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}" # from authelia
        GF_SECURITY_COOKIE_SAMESITE: "{{ .GF_SECURITY_COOKIE_SAMESITE }}"
        # GF_SERVER_ROOT_URL: "{{ .GF_SERVER_ROOT_URL }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: postgres-v16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: authelia
    - extract:
        key: postgres
