---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      sabnzbd: # this can now be any name you wish
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app: # this can now be any name you wish
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.3.3@sha256:4ad73733ae11eb03852ba99d6e49bff93f8087f9f77b9b193a1063c3f6f31482
              # repository: lscr.io/linuxserver/sabnzbd
              # tag: latest
            env:
              TZ: ${TIMEZONE}
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.media,
                sabnzbd.media.svc,
                sabnzbd.media.svc.cluster,
                sabnzbd.media.svc.cluster.local,
                {{ .Release.Name }}.${SECRET_DOMAIN}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api?mode=version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            # resources:
            #   requests:
            #     cpu: 15m
            #     memory: 110M
            #   limits:
            #     cpu: 15m
            #     memory: 110M

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            # supplementalGroups: [10000]

    service:
      app: # this can now be any name you wish
        controller: sabnzbd
        ports:
          http:
            port: *port

    ingress:
      app: # this can now be any name you wish
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Sabnzbd"
          gethomepage.dev/description: "Free and easy binary newsreader"
          gethomepage.dev/group: "Media"
          gethomepage.dev/icon: "sabnzbd.svg"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      media:
        enabled: true
        existingClaim: nfs-synnas-media-pvc
        globalMounts:
          - path: /media
        # mountPath: /media
      # incomplete:
      #   enabled: true
      #   existingClaim: sabnzbd-incomplete
      #   globalMounts:
      #     - path: /incomplete
