---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sabnzbd-backup
  namespace: media
spec:
  sourcePVC: config-sabnzbd-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: sabnzbd-restic-secret
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    # default lsio user abc
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: sabnzbd-restore
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: sabnzbd-restic-secret
    destinationPVC: config-sabnzbd-0
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    restoreAsOf: 2023-08-30T10:00:00+02:00
