---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .MOSQUITTO_MQTT_USERNAME }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .MOSQUITTO_MQTT_PASSWORD }}"
  dataFrom:
    - extract:
        key: mosquitto
    # - extract:
    #     key: zigbee2mqtt
