---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt-zstack
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      zigbee2mqtt-zstack:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            securityContext:
            # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
              privileged: true

            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 1.35.3
            env:
              TZ: "{$TIMEZONE}"
              ZIGBEE2MQTT_DATA: /config
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
              ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: debug # info
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
              ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
              ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
              ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
              # ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 8080
              ZIGBEE2MQTT_CONFIG_FRONTEND: "true"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
              ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
              ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
              ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "false"
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://10.200.0.100
              ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              # ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
              # ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyUSB0
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: zstack
              # ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/ttyACM0
              # ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: deconz
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret
            # resources:
            #   requests:
            #     cpu: 63m
            #     memory: 110M
            #   limits:
            #     cpu: 63m
            #     memory: 110M

        pod:
          # securityContext:
          #   # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
          #   privileged: true
          nodeSelector:
            # aeotec.feature.node.kubernetes.io/zwave: "true"
            zigbee-controller: "true"
          # affinity:
          #   nodeAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       nodeSelectorTerms:
          #         - matchExpressions:
          #             - key: zigbee-controller
          #               operator: In
          #               values:
          #                 - "true"

    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 568
    #     runAsGroup: 568
    #     fsGroup: 568
    #     fsGroupChangePolicy: OnRootMismatch
    #     seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: zigbee2mqtt-zstack
        ports:
          http:
            port: 8080

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Zigbee2MQTT"
          gethomepage.dev/description: "Zigbee to MQTT bridge"
          gethomepage.dev/group: "Home Automation"
          gethomepage.dev/icon: "zigbee2mqtt.svg"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_28006491eda5ed119e06efa32981d5c7-if00-port0
        globalMounts:
          - path: /dev/ttyUSB0
      # usb:
      #   enabled: true
      #   type: hostPath
      #   hostPath: /dev/ttyACM0
      #   globalMounts:
      #     - path: /dev/ttyACM0
