---
apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  # labels:
spec:
  selector:
    app.kubernetes.io/instance: coredns
    k8s-app: kube-dns
    app.kubernetes.io/name: coredns
  clusterIP: 10.43.0.10
  ports:
    - name: udp-53
      protocol: UDP
      port: 53
      targetPort: 53
