---
apiVersion: v1
kind: Namespace
metadata:
  name: home-automation
  annotations:
    volsync.backube/privileged-movers: "true"
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    goldilocks.fairwinds.com/enabled: "true"
