apiVersion: v1
kind: PersistentVolume
metadata:
  name: truenas-nfs-media-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${TRUENAS_IP}
    path: "/mnt/spinning-raid/media"
  mountOptions:
    - nfsvers=4
    - hard
    - noac
    - nocto
    - noacl
    - rsize=8192
    - wsize=8192
    - async
    - retrans=3
    - timeo=600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: truenas-nfs-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: truenas-nfs-media-pv
