---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.14.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podLabels:
      release: *app

    securityContext:
      privileged: true

    autoDirectNodeRoutes: true
    bandwidthManager:
      enabled: true
      bbr: true
    bpf:
      # clockProbe: true
      # lbExternalClusterIP: true
      masquerade: true
      # tproxy: true
    # bgp:
    #   enabled: true
    #   announce:
    #     loadbalancerIP: true
    cluster:
      id: 1
      name: hekate
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: false
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: nginx
          hosts:
            - &host hubble.${SECRET_DOMAIN}

    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: ${CLUSTER_CIDR}
    k8sServiceHost: ${KUBE_VIP_ADDR}
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true

    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: false
        annotations:
          grafana_folder: Cilium

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true

    dashboards:
      enabled: false
      annotations:
        grafana_folder: Cilium

    rollOutCiliumPods: true
    tunnel: disabled

    # nodePort:
    #   enabled: true
    # enableCiliumEndpointSlice: true
    # enableK8sEndpointSlice: true
    # enableIdentityMark: true
    # ingressController:
    #   enabled: true
    #   loadbalancerMode: dedicated
    #   defaultSecretName: "${SECRET_DOMAIN/./-}-production-tls"
    #   defaultSecretNamespace: networking
    # gatewayAPI:
    #   enabled: false
    bgpControlPlane:
      enabled: true

    # # hostFirewall:
    # #   enabled: true
    # # hostPort:
    # #   enabled: true
    # # socketLB:
    # #   enabled: true
    # # wellKnownIdentities:
    # #   enabled: true
    # # enableCnpStatusUpdates: true
    # # endpointStatus:
    # #   enabled: true
    # #   status: "policy"

    # l7Proxy: true



