---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.14.3
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    podLabels:
      release: *app

    securityContext:
      privileged: true
    autoDirectNodeRoutes: true
    # annotateK8sNode: true
    cluster:
      id: 1
      name: hekate
    bpf:
      clockProbe: true
      lbExternalClusterIP: true
      masquerade: true
      tproxy: true
    # bgp:
    #   enabled: false
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true
    nodePort:
      enabled: true
    enableCiliumEndpointSlice: true
    enableK8sEndpointSlice: true
    enableIdentityMark: true
    ingressController:
      enabled: true
      loadbalancerMode: dedicated
      defaultSecretName: "${SECRET_DOMAIN/./-}-production-tls"
      defaultSecretNamespace: networking
    gatewayAPI:
      enabled: false
    bgpControlPlane:
      enabled: true
    l2announcements:
      enabled: false
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s

    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          # annotations:
            # kubernetes.io/ingress.class: cilium
            # cert-manager.io/cluster-issuer: letsencrypt-production
          # className: internal
          className: nginx
          hosts:
            - &host hubble.${SECRET_DOMAIN}
          # tls:
          #   - hosts:
          #       - *host
    rollOutCiliumPods: true
    # hostFirewall:
    #   enabled: true
    # hostPort:
    #   enabled: true
    # socketLB:
    #   enabled: true
    # wellKnownIdentities:
    #   enabled: true
    # enableCnpStatusUpdates: true
    # endpointStatus:
    #   enabled: true
    #   status: "policy"
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: ${CLUSTER_CIDR}

    loadBalancer:
      algorithm: maglev
      mode: dsr
      serviceTopology: true
    l7Proxy: true
    localRedirectPolicy: true
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    k8sServiceHost: ${KUBE_VIP_ADDR}
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    tunnel: disabled

    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium

    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true

    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium

