apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
  namespace: media
spec:
  storageClassName: media
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: "/volume1/media"
  mountOptions:
    # # - nfsvers=3
    # - tcp
    # - intr
    # # - hard
    # - noatime
    # - nodiratime
    - nfsvers=4
    - hard
    - noac
    - nocto
    - noacl
    - rsize=8192
    - wsize=8192
    - async
    - retrans=3
    - timeo=600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media
  resources:
    requests:
      storage: 1Mi
