---
kubernetes:
  children:
    master:
      hosts:
        brix-01:
          ansible_host: 10.200.0.31
          ceph_drives:
            - /dev/sda3
        brix-02:
          ansible_host: 10.200.0.32
          ceph_drives:
            - /dev/sda3
        brix-03:
          ansible_host: 10.200.0.33
          ceph_drives:
            - /dev/sda3
    worker:
      hosts:
        brix-04:
          ansible_host: 10.200.0.34
          ceph_drives:
            - /dev/sda3
