---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
  namespace: media
spec:
  sourcePVC: config-sonarr-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: sonarr-restic-secret
    cacheCapacity: 10Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    # default lsio user abc
    moverSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: sonarr-restore
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: sonarr-restic-secret
    destinationPVC: config-sonarr-0
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 10Gi
    cacheStorageClassName: local-path
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
