---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
  # - ./pvc-config.yaml
  - ./zigbee2mqtt-devices.sops.yaml
  - ./secret.sops.yaml
  - ./helmrelease.yaml
