---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-config-v3
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: nfs-client
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
