# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    ZIGBEE2MQTT_CONFIG_DEVICES: ENC[AES256_GCM,data:SptodIqlnFuXNxnGbc+XUas26UBfwYdmzC/cpNId5N+h/8UJPsRChXeLmyDUWu/P6artVD0ADORrzrZ05BBkflH6YzBhbvyXr+o05ZFKnoOLZpw1CQS/KCEksvXKWVGPV0cOr9F+gt5zNOf6RAW5wem++SAT6HmgripTZ6kwKENHruJFfceP28XDJiX3lYosxIWMitAcKqoTAJQLT8SMRlmPaltuYkxWXUozvwdy5afViTJWjDS+KkK+78ZC8Hj7tloI2trhLPyCE38xLvqcpx95oJYQvjh0DEa0H4DfAtkV7ZHaWqgjvCq6lClNENdC+IhHIcDhP4OuFJ4ha++8EzgxbmQPl3mLxiG3PHbOkVLmaAG9Gc0aGjoOKzidUNKX7gFiwM2yLgWOVFFSeATtnVOQ9tKdxU44wpXFwgJJDTNhEwM8PERpwxCaYhdG3S48tBOJBcZge6TnwAXVfFdtc9RoeFf5691jzMWYaSd1uytRKdGPQfSjP4SwQ+BNR5CoiZc3qMdtv+6JBNpddPCQNAKucd479j2yhe0hzWLnccBapOEzTWDDmWv395M=,iv:hGX9b87oc73mAoLTcaAAcXu6kTur5RDeSO5Li+tdoGQ=,tag:hnvN+xrg14C3u5xevw3EXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOXE5dEhIQmpmN1J4a09q
            ZHppYVNpWnIvdW5GT3gwTkVHaENPRk1lOEJzCm1ac1dURURlSHd3c1RjS0g3cFlF
            ellTQmZIcnVmaHd5U3ViaDhxSUlwYVUKLS0tIGt4VHpTQ3BNU2dzT2RIWjJ4MHB4
            dmpKSGlkdFc5ZDhBNm5IQVZsMXg4UG8Kc5K1ITEi+z+ymKv8jacggQXHbeH9HQkZ
            JBmT2TPiGpcnAEBUE8nc/0qpVoR0aSnFN/XB8PeKbSa5q1wT9U4Npg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T22:51:20Z"
    mac: ENC[AES256_GCM,data:y6WKVwBXbJaYH820NOVLugjqZ3WSeburgZJovGOl1FdjJ11XgG0hYgXR2YmhkTo5TP+SgPZVWMxoOvYmuJlQgmMHUQ3MP3+cqeCBDuG2l4YRicYcr4k6q93ELCvD4zYpUV3emkbGIjdlCy5z7jYss1mLxSqTpXihckQXLi5cOkQ=,iv:jsZLQauJ+UaVChvnUAMGCRzyrcbV8dPZqHyrVa37hPE=,tag:07GMtcQ8X1kIWtyr34z49w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
