# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: home-automation
stringData:
    devices: ENC[AES256_GCM,data:7/ERCrSTQcOpLQFwq/sd7wxy7ZtV5ZGHQ4EBb41u74047KdZIryDsa6cX5VMSC5nOuVGIzqdHdJVu1rXh5k5EiaLw8H54aWH/QhSmVTcFtEZjrB2RutOOvjoJ4LIo987mVuPaBSOa/5PBSZ4Cy08RVKvAMjSPY1Uu3Jnzl6PTAT6PAIMA1Sas/6uP2N8gTEtuuiEvgZlx8NGmIOa3ykuYE05TcQgQhqvQRflOpIpw2OybJOiYAMexQucUx/VoAuo6POk0BwkpaFRovu3DacAx3k2+AZFoQtJo0xklUUsUxuK+kb7A/aFVO5yt6DExhkA0bBn/bXbZI07dy2iHBse/aCplm8k0v+X0A9S+lIY/sxlRM0yswld1dBaMNZDw7ZlYRIJ0jXL8I2/h1YbXSqwV877Leb3f9L7mJNCVa7HdihkKv3HHBLEvCorWxrXbW9Nsi+7TdvnH1JYvp2Pf2GuWQfe6OqcIWHg0nO+OePqui1jJ+zVayCiic64Rr4FgXt8WOARxGKPkHzZMh0B1P+/+67TOx0acBChr9ayM3JEi6Z7zz8jLQMjGSqurQ8=,iv:4ycRAC0n7Szf7XPQn6mV2sNexzE2x6UDTJM2igSYGxI=,tag:tUylC0GVbWiqXZUIyHLQDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOXE5dEhIQmpmN1J4a09q
            ZHppYVNpWnIvdW5GT3gwTkVHaENPRk1lOEJzCm1ac1dURURlSHd3c1RjS0g3cFlF
            ellTQmZIcnVmaHd5U3ViaDhxSUlwYVUKLS0tIGt4VHpTQ3BNU2dzT2RIWjJ4MHB4
            dmpKSGlkdFc5ZDhBNm5IQVZsMXg4UG8Kc5K1ITEi+z+ymKv8jacggQXHbeH9HQkZ
            JBmT2TPiGpcnAEBUE8nc/0qpVoR0aSnFN/XB8PeKbSa5q1wT9U4Npg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T22:48:58Z"
    mac: ENC[AES256_GCM,data:X5bF+pvtbufLm/xWJ7ixLMv1B02/lyhflMpdYDn2Ri3QmupDaw4LPKfzZxB2To9HgGBidvQBEg8csc3lbMbhUDVgmV62ZTVizxqBSI6mNP0IOkiwiOexfv7sNx85JYbIPKg7VRPgHjyD7axSPaAEdu97aWOSu7hV3CTty/JwfCU=,iv:VR0PTEWwakBUKlPQ/hgk5D+bWi+ZQY7tZVXeHqAAgLc=,tag:TwALTbeFxPTlvlk4mT2cjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
