---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt-backup
  namespace: default
spec:
  sourcePVC: config-zigbee2mqtt-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: zigbee2mqtt-restic-secret
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 7
      within: 3d
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: zigbee2mqtt-restore
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: zigbee2mqtt-restic-secret
    destinationPVC: config-zigbee2mqtt-0
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    storageClassName: ceph-block
