apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:V+zJ639oApL9JY85BFOevQpTVkvvUnvNNfQ6r42q3kvYXQkJiWUA2Q==,iv:9WrH5/yFRhXYxxTBTk3WQlOUdTRNEuQhp0VnUQWcgQU=,tag:/73Zn+mMkEoBZeqI7/D/Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ1dUSEVvQTE2WTBUeTdh
            cXRPckgvNTNDNDNjR2wxMHZ5d2w1MStaWVNFCjVuL3l1WVJpbmo4K0J6WVpYTkpv
            UTJMcEgyMm1ab2lKcm9Zdis0Nmg3cjQKLS0tIC9namZ3djF6T1JZaTNrQ2tKZFFj
            ZUJaQVI1ZEtBdnJXeFhTblFLeXJoQ3MKS4NIACAxFv/FkJkiBMeXxIHKTU72lqFd
            Y9FPWyTiHR3k46xBRVVDcVAIZ7YO3hIq2GV4IPUVGR8iq8gUCsUR7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T04:31:05Z"
    mac: ENC[AES256_GCM,data:t2SirhdWa8q1kWaLRrV265TWiouce7lvWw69t6dAKV3kTSrXYko5zbxA/CbcEofnCDLotKVX8Cw6lvMwOro7gc97lDutqxkHh7Rj+uuzR+UEzb8AtQld7+gEUnegxYHGAb+wltsh0+BMI3D4iQq87+59+XZsqbgxuAgS0+ChmQE=,iv:VY8Qhc3utzbrmknq4uGLZhSQLT3JCxPaqmxChPQEDxg=,tag:FB9wAMPoVQf951f+HntKWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
