---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph
      version: v1.14.9
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    csi:
      csiAddons:
        enabled: false # Set to true when using kubernetes-csi-addons
    monitoring:
      enabled: true

    # resources:
    #   requests:
    #     cpu: 600m
    #     memory: 256Mi
    #   limits:
    #     cpu: 600m
    #     memory: 512Mi
    resources:
      requests:
        cpu: 109m
        memory: 204M
      limits:
        memory: 453M
