apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:I+BXM9k=,iv:MmXMXV1SeXblTFzeuv0DjpbSOgBzFSa243qyEDagxSU=,tag:07S6Mxi4iXPvCZMCkXdokQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQUFZQ1VEWmx3QXNwNGx1
            YnVsSFEzSjVMbG1GS3dUQ0xJY3dCaWdPc21JCi9RVFFkSldWb1E2RTFWbmtEV1Uy
            YVp2Q2U5ZTVVSDVKOXYraVBHSmVJRmcKLS0tIDBaS2N2MUtJWnFLRmZRMms2ZkM2
            eXRmR2dteGxuY3hZYy8xelJxVnpDbWMKFSjZleuA7b7W77JgBBCIxuRQT38hTZEN
            0i0kHAP8EQfr/1/NQuGeoStobIMDuCSR8TLkbi56zcQerXF+e0+FeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T04:31:05Z"
    mac: ENC[AES256_GCM,data:CvrP7S3NOzQVHlfb1XNCe19pIxeLJyT/Oru9ags0/PG/7wfpSHIQP+TWcXKOZRiLdVGSVkXjPM+dzYasDZ7fDaSbP4qa6SlTbhB9fpeStkbsyBsNVesgckAbKK6jbs0B7YQmu1W5GwJW5Vk+UOGyhHmExRbfv/frO58Ehe+nQWM=,iv:mI0kDPJNdTFRVPK6clY5blKQ7TQPNndHzqwCjhy4e2Q=,tag:xZMpMvLaWCQvHhFAfWqI8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
