apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:I+BXM9k=,iv:MmXMXV1SeXblTFzeuv0DjpbSOgBzFSa243qyEDagxSU=,tag:07S6Mxi4iXPvCZMCkXdokQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQUFZQ1VEWmx3QXNwNGx1
            YnVsSFEzSjVMbG1GS3dUQ0xJY3dCaWdPc21JCi9RVFFkSldWb1E2RTFWbmtEV1Uy
            YVp2Q2U5ZTVVSDVKOXYraVBHSmVJRmcKLS0tIDBaS2N2MUtJWnFLRmZRMms2ZkM2
            eXRmR2dteGxuY3hZYy8xelJxVnpDbWMKFSjZleuA7b7W77JgBBCIxuRQT38hTZEN
            0i0kHAP8EQfr/1/NQuGeoStobIMDuCSR8TLkbi56zcQerXF+e0+FeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-15T15:00:37Z"
    mac: ENC[AES256_GCM,data:6PjsMGG6BBSiuGbr/qMzwMZZAlE+n+/nkpDx1YwdhCRIItaLnDs5fDlKwKduDLMFIlv0o3pWhzoYObuGTS1UjR4ezp4dhSL4N8zklTphGJZVpLYP0ISVbCsDoYyPOTARCNxu/fO37tGj4OCti9rL5d3XFtKOveSwvMgTosglzio=,iv:x+JO5s3H8u3fqLt0J4nBrKbrjK85h3Z9T03T2QIgLZs=,tag:DTvZy9phPsftZevMMz6d2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: hekate-ca-tls-secret
    namespace: cert-manager
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:l09YGoA2miZ33LvfELXxrzGVOah1mLlxuk2dAbRlPzqFRF6AsQTMItVkUw4d061TP5KQKQE73foaJxMmEUbNTLYpkS1kRem4vOV6afCyl8EgNon16oK77zSTY7ilXQqiz+9e+rlfQDHgTIY+8x1E7q+1+wYzQiBY6F40C8LUvPuPfO/XU1ZRcTI9wN8ifGlCoaxXWZzj0RKnLL+Ryk5qYHOydRqvWGtIYOPs0lI95AwEF5ilb+b9qFz1f5u3pKNzPtoIaG72a1+gYeaqI0gMi7OQVt7qPghhfiXZFIjiX3yzmtT4MGv148kgOq2ZVCJAX57T/mA2A8XqGuM2jFu7awn2LXzcmdkM6shsFZyVQMuKxSRrm1p1QYKA4/4cG5IVuFM0Md7o6VPVf/+I0SLXVQQwcw5CU5WU61yYkJewo1B6wR7RagU59wCUli+Npa7TF9gE8AokXMLRv/pSEVI6KvLwkDDrDmukg3r4nOCudQ2bGvGZv29jGl5oJhde+qXYDlL4kx98ZeDCGWzv6e7fjP02B6SLu1XPPGXmDhFtsXKQmap+w774U/hEnfhYSOh8gyDFTgoO9FdAjmdyeTgq8CCHLKPglnNf6KY3tzLg4ZWS4M/8qkNlW9GjQHl12qAliqd1iqPv44fKY/SV4yQrrcO/9qNpCwLuwTNq676ZW7niYJaks5t+fDTW8XBXYtBk32nEekbShybLvZtMe6u2iJQGzjJM81Ir1xGHbYRp7TT2WgW4idMOKTHk2ZIcDgTRBJ22TyR7wy4hdXAInbL3Zvzvqv6KJzxIQ8/3DWNu3maf5YbbpDuEdONWPCgHKQWd3a5H3fXRsGKkpoLH93blIU7HMMflsuYawO0WzvNjiWSknTlhTJKypMVdrJoj/J41yj6XInH0ktSiPVcwbwfkVLDjDg9tg94u/JatLS9YH2Xx8BIVFh5bvA==,iv:37Om8Dkr2S5McFMRTnReJOBCB0+cBGM2j9VxfeJ19No=,tag:iZij9jvbYmKZPvo0kktB5w==,type:str]
    tls.key: ENC[AES256_GCM,data:aI0FRD8gcrgboViALB3yTmULHUo+RmW6rMvH2M+Tr0IIvu7Ri0SSbZnTY50TwStWDAMgjN9yprMDEjHaET8pnguN37tGjmnlgG4iZctq+FHXsgzbXcSMk24nVXxPwcTImKinEP/EGKO5PepuUhtkUrPRedfbFJWHbAUmT+ESxhgX9L81hm1rfwu0kAXZmAtqLWQE6/SEoLWK6b39zBRNocyQt4XvnACWq0nJkVQIAnytrnjCjGP8FMw8h+JeQQ7KS/88cAJyV4+cuGp6l4N40K2Ig9RIGHwCBRQxXoLq0Tr9KP0RnjQblrTOepibLaoB,iv:uPbrNKjlrbiK7tvkbw43feeThDrOqwgPWYVxBGAkr30=,tag:vkn+s+Vk6DsZ8dADRLfjow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQUFZQ1VEWmx3QXNwNGx1
            YnVsSFEzSjVMbG1GS3dUQ0xJY3dCaWdPc21JCi9RVFFkSldWb1E2RTFWbmtEV1Uy
            YVp2Q2U5ZTVVSDVKOXYraVBHSmVJRmcKLS0tIDBaS2N2MUtJWnFLRmZRMms2ZkM2
            eXRmR2dteGxuY3hZYy8xelJxVnpDbWMKFSjZleuA7b7W77JgBBCIxuRQT38hTZEN
            0i0kHAP8EQfr/1/NQuGeoStobIMDuCSR8TLkbi56zcQerXF+e0+FeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-15T15:00:37Z"
    mac: ENC[AES256_GCM,data:6PjsMGG6BBSiuGbr/qMzwMZZAlE+n+/nkpDx1YwdhCRIItaLnDs5fDlKwKduDLMFIlv0o3pWhzoYObuGTS1UjR4ezp4dhSL4N8zklTphGJZVpLYP0ISVbCsDoYyPOTARCNxu/fO37tGj4OCti9rL5d3XFtKOveSwvMgTosglzio=,iv:x+JO5s3H8u3fqLt0J4nBrKbrjK85h3Z9T03T2QIgLZs=,tag:DTvZy9phPsftZevMMz6d2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
