---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app omada-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      omada-controller:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: mbentley/omada-controller
              tag: 5.14
            env:
              TZ: ${TIMEZONE}
              # TZ: Europe/Amsterdam
              # PUID: 508
              # PGID: 508
              SHOW_SERVER_LOGS: true
              SHOW_MONGODB_LOGS: false
              # SSL_CERT_NAME: tls.crt
              # SSL_KEY_NAME: tls.key
            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 250Mi
            #   limits:
            #     # cpu: 476m
            #     memory: 2000Mi

    service:
      app:
        controller: omada-controller
        type: LoadBalancer
        # externalTrafficPolicy: Local
        externalTrafficPolicy: Cluster
        annotations:
          # metallb.universe.tf/loadBalancerIPs: ${LB_OMADA_CONTROLLER}
          io.cilium/lb-ipam-ips: ${LB_OMADA_CONTROLLER}

        ports:
          http:
            # port: &port 8088
            port: 8088
          manage-https:
            enabled: true
            # nameOverride: manage-https
            # port: 8043
            port: &port 8043
            protocol: HTTPS
          portal-https:
            enabled: true
            port: 8843
            protocol: HTTPS
          app-discovery:
            enabled: true
            port: 27001
            protocol: UDP
          adopt-v1:
            enabled: true
            port: 29812
            protocol: TCP
          upgrade-v1:
            enabled: true
            port: 29813
            protocol: TCP
          manager-v1:
            enabled: true
            port: 29811
            protocol: TCP
          manager-v2:
            enabled: true
            port: 29814
            protocol: TCP
          discovery:
            enabled: true
            port: 29810
            protocol: UDP

    # probes:
    #   liveness: &probes
    #     enabled: false
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /ping
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "D-Link"
          gethomepage.dev/description: "Omada-SDN Netzwork"
          gethomepage.dev/group: "Apps"
          gethomepage.dev/icon: "d-link.svg"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: *port

    persistence:
      data:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /opt/tplink/EAPController/data
      work:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /opt/tplink/EAPController/work
      logs:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /opt/tplink/EAPController/logs
