---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: esphome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: esphome-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |-
          wifi_ssid: "{{ .WIFI_SSID }}"
          wifi_pwd: "{{ .WIFI_PASSWORD }}"
          # wifi_fallback_ssid_password: "{{ .WIFI_FALLBACK_SSID_PASSWORD }}"

          mqtt_host: mqtt
          # mqtt_host: mqtt.home-automation.svc.cluster.local
          # mqtt_user: "{{ .HASS_LONGITUDE }}"
          # mqtt_pwd: "{{ .HASS_LONGITUDE }}"

          # domain_devices: "{{ .HASS_LONGITUDE }}"

          # dsmrreader_apikey: "Token {{ .HASS_LONGITUDE }}"
  dataFrom:
    - extract:
        key: esphome
