---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app esphome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      esphome:
        annotations:
          secret.reloader.stakater.com/reload: esphome-secret



        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2024.8.3
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            # resources:
            #   requests:
            #     cpu: 48m
            #     memory: 443M
            #   limits:
            #     memory: 709M

        # pod:
        #   securityContext:
        #     runAsUser: 568
        #     runAsGroup: 568
        #     fsGroup: 568
        #     fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "ESPHome"
          gethomepage.dev/description: "Control your microcontrollers"
          gethomepage.dev/group: "Home Automation"
          gethomepage.dev/icon: "esphome.svg"
        hosts:
          - host: &host "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: *app
        advancedMounts:
          esphome:
            app:
              - path: /config
      # secrets:
      #   type: secret
      #   name: esphome-secret
      #   globalMounts:
      #     - path: /config/secrets.yaml
      #       subPath: secrets.yaml
      esphome-cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
      # deploy-key:
      #   type: secret
      #   name: esphome-deploykey
      #   defaultMode: 256
      #   globalMounts:
      #     - path: /root/.ssh/id_ed25519
      #       subPath: id_ed25519
