---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ombi
  namespace: media
spec:
  sourcePVC: config-ombi-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: ombi-restic-secret
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    # default lsio user abc
    moverSecurityContext:
      runAsUser: 911
      runAsGroup: 911
      fsGroup: 911
    retain:
      daily: 7
      within: 3d
