---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openproject
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: openproject-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        # Postgres
        password: "{{ .OP_POSTGRES_PASS }}"
        postgres-password: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: openproject
    - extract:
        key: postgres
