---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app openproject
spec:
  interval: 30m
  chart:
    spec:
      chart: openproject
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: openproject
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    # openproject:

    postgresql:
      bundled: false
      connection:
        host: postgres-v16-rw.database.svc.cluster.local
        port: 5432
      auth:
        existingSecret: openproject-secret
        secretKeys:
          adminPasswordKey: "postgres-password"
          userPasswordKey: "password"

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        hajimari.io/group: "Apps"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "LLDAP"
        gethomepage.dev/description: "Light LDAP implementation"
        gethomepage.dev/group: "Apps"
        gethomepage.dev/icon: "mdi-account-group-#cf2e2e"
      host: openproject.${SECRET_DOMAIN}
      # hosts:
      #   - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
      #     paths:
      #       - path: /
      #         pathType: Prefix
      #         service:
      #           name: main
      #           port: http

    persistence:
      enabled: true
      storageClassName: ceph-filesystem
