---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: actions-runner-controller-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .github_app_private_key }}"
        github_app_installation_id: "{{ .github_app_private_key }}"
        github_app_private_key: "{{ .github_app_private_key }}"
  dataFrom:
    - extract:
        key: github-actions-runner-controller
