---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-v16
spec:
  # daily, 1am UCT
  schedule: "0 0 1 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres-v16
