apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: bookstack
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: bookstack
    key: password
  maxUserConnections: 20
