---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: mariadb-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        username: "{{ .MYSQL_SUPER_USER }}"
        password: "{{ .MYSQL_SUPER_PASS }}"
        # aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        # aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: mariadb
