---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./secrets.sops.yaml
  - ./mariadb.yaml
  - ./bookstack-database.yaml
  - ./bookstack-grant.yaml
  - ./bookstack-user.yaml
