---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx
      version: 5.6.1
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: public.ecr.aws/emqx/emqx

    replicaCount: 3
    recreatePods: true

    emqxConfig:
      # EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain

    emqxAclConfig: >
      {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
      {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
      {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
      {allow, all}.
    emqxLoadedPlugins: >
      {emqx_management, true}.
      {emqx_recon, true}.
      {emqx_retainer, true}.
      {emqx_dashboard, true}.
      {emqx_telemetry, false}.
      {emqx_rule_engine, true}.
      {emqx_bridge_mqtt, false}.
      {emqx_auth_mnesia, true}.
      {emqx_prometheus, true}.
    emqxLoadedModules: >
      {emqx_mod_presence, true}.
      {emqx_mod_delayed, false}.
      {emqx_mod_rewrite, false}.
      {emqx_mod_subscription, false}.
      {emqx_mod_topic_metrics, true}.

    service:
      type: LoadBalancer
      loadBalancerIP: "${LB_EMQX}"
      externalTrafficPolicy: Local

    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "EMQX"
          gethomepage.dev/description: "MQTT Broker"
          gethomepage.dev/group: "Home Automation"
          gethomepage.dev/icon: "emqx.svg"
          gethomepage.dev/app: "emqx"
        path: /
        pathType: Prefix
        hosts:
          - &host "emqx.${SECRET_DOMAIN}"

    metrics:
      enabled: false

    # persistence:
    #   enabled: true
    #   existingClaim: emqx-data-v4
      # storageClass: ceph-block
      # size: 100Mi

    # affinity:
    #   podAntiAffinity:
    #     preferredDuringSchedulingIgnoredDuringExecution:
    #       - weight: 100
    #         podAffinityTerm:
    #           labelSelector:
    #             matchExpressions:
    #               - key: app.kubernetes.io/name
    #                 operator: In
    #                 values:
    #                   - emqx
    #           topologyKey: kubernetes.io/hostname

    # resources:
    #   requests:
    #     cpu: 63m
    #     memory: 226M
    #   limits:
    #     cpu: 63m
    #     memory: 226M

  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: ADMIN_PASSWORD
    # - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
    #   kind: Secret
    #   name: emqx-config
    #   valuesKey: user_1_username
    # - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
    #   kind: Secret
    #   name: emqx-config
    #   valuesKey: user_1_password
