---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-data-v3
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
