# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: emqx-config
    namespace: home-automation
stringData:
    admin_password: ENC[AES256_GCM,data:sZ9leLQZVVU=,iv:Kz2wzcMHykvR0ZIbNTUYV+vjP33XRNTsvnm9miw8AoM=,tag:eYjPDQowFVtl7XhzclNFOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadWorSFgzelRSb3lBYzRB
            WWFBRExZQW5wQkM5OU1Fdy9FUVVqaHp4MG1nCkVjOXFLWWNyU2xqVUh1VGpKN0VV
            Wm9kK29TL29mTTZ6T2V2NTZXd3psNzAKLS0tIHBsbERnS0plb3RkZnNXYjNaUTl0
            clBNNFNueTJ0TjZWL2FLay9mUDNyVHMKLr11uDPmA6qQYxG8v1NvqXjxh1+A/OeS
            FOLhjecrLA4RzfFCzH7tTVEik3jMg4V0ZGVM/ghB6sZhJhlrR3+AZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T14:29:47Z"
    mac: ENC[AES256_GCM,data:i/DPzwmXtVq49ralcfVu0/Wz2+0lIuKFiK5IL+TfxD1zNQjPRVvHZLscZfd8aF7pgQW7tAMabAe/zP6veGsfvmdE03wvOSMhgzmdT31Y+yX7XXezIwZ3IHbcs4/nqDTlqhvsKNhC/rC9Q7dkqjM7sGRTZcRhPhadXs6RYREQiQY=,iv:7iSmfS0aq/eU4CZw+Nbvgt2q3b3eUu4074oxOCTVLFE=,tag:jD3R8HbySvf81YjioaMyQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
