---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: 3.2.4
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    crds:
      install: true

    # customLabels:
    #   release: *app

    grafana:
      enabled: true
      annotations:
        grafana_folder: System

    backgroundController:
      podLabels:
        release: *app
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: *app
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - patch
                - delete
                - get
                - list

    cleanupController:
      podLabels:
        release: *app
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: *app

    reportsController:
      podLabels:
        release: *app
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: *app

    admissionController:
      podLabels:
        release: *app
      replicas: 3
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: *app
      rbac:
        clusterRole:
          extraResources:
            - apiGroups:
                - ""
              resources:
                - pods
              verbs:
                - create
                - update
                - delete
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: DoNotSchedule
      #     labelSelector:
      #       matchLabels:
      #         app.kubernetes.io/instance: kyverno
      #         app.kubernetes.io/component: kyverno
