apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:kMb57EqqjnJJVOjinWsw56TiUYf+u+IZokg1UutFx8ziNIS27VKzPIXDhDhd3YGdJ9aagL20BMubPEIY,iv:5NTDOwlarUqGhn4UylZ9cZM/s9AKw8kE4/m1/x6cig4=,tag:PCLHVe3lpmidTHmoW0JJ1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTHpwZzY3dFFsZWZVZkl5
            ZnZiNEo5UGREM3JxMFQwaUdwbmNnSUZlOVZzCkRpbGltMUFsRlhHQVltbnJxejAv
            RDlWMU52QkYxcVRuU1JHWkxsMFNmME0KLS0tIENFeUZ3eGpSclVhRnNER3FMRWcy
            blRwaWV3aVdhRGRCR0J1NU1FQXRqam8K24I6rXOUD3Dv1Pz64QziE+VS4Nsii7/V
            7zZIP27uTEpnWD8JXn5PkPnYRTMlDg/m/PRolWjRPSiiuSybvi2e/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T22:43:08Z"
    mac: ENC[AES256_GCM,data:UEUoJ109cbNgYf4YbIA2HpM8yicP9DVgMiRsAfaqr8fI/eP/Ph7Mzct45APi8dz/gFwiki8hP1HMCgOp6XMf4MHx3knRk0bRzN2lxj+/TmevGhFX8Hyxk4o5Uo5mHWaKl3J6qGPZ9iYS9A6Cn8px+SdyNbicehfnysSvDfSihMU=,iv:kQJeMh3D+iHM4PesyachHuwJUKRqtKi8+Tb7Qb9L/Jw=,tag:4AT+blH7Bf2Aqz3VPO/Jgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
