# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: bookstack-secret
    namespace: default
stringData:
    DB_HOST: ENC[AES256_GCM,data:FNy+YtQf4WGOxYpuYcyOZA==,iv:JB3712Iux1boN3YjjQ1BqkDVT3ljWh1eErGwqykl9Sw=,tag:THtt46zLogt6gGhJv5MLKg==,type:str]
    #ENC[AES256_GCM,data:QJ8mk+gL2V0ud/1UDUQ=,iv:uhK06zCT1qZ7KfYVae0i6f9A+6c269FxFlC9XebrOUg=,tag:c3PdBead3TBObZrNxmXh4g==,type:comment]
    DB_USER: ENC[AES256_GCM,data:EIdqxNA566tXLJMIyHc=,iv:AkdETORcLxuQV0gym7Sh6dRcAlxeypyC9K3j0p2LO9M=,tag:lS4PsAL8ftqueJESh5M6Yg==,type:str]
    DB_PASS: ENC[AES256_GCM,data:+N0jhs+ICerSGY1hTkqeC9ywqSW1MF8ZdC3GrZrZrKA=,iv:e9ATKH9IWLRGucqkb6EX4A/AYU/Gjw+KDL1lXOIEMf0=,tag:prfboozXdlJsY+DInjiSdw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:9JCrwnvMRtwErfXGlkY=,iv:pSP0wtuHuc+iz7RZ4mpRsuTwmO0m0de9ch9RBnz5Mxs=,tag:5GbAqijuOaHbNrHk3wya4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMXgzLzV1TTM5VlRwL21C
            QWVzZWVUT2t3OEN3VXBrT2ZNY0lkSW00QndzClFTY2NEUzBlUy9Qa1FHNWJBc1Q2
            SytJMjFURTcyakloamJxcUh4RWpveW8KLS0tIHpiaXZkK2xhanVacXNtNnYyTFc2
            bzRjT0ZXVlNWdFVyMjZpTVpseUFZRk0KC0yNsTl5uHtiAZn58vqxksK9J0Jpuddd
            db2IeZ2lL669d/GtMIWDNLC6Z0vo8B2w/j3umeDzINFyrF34eY2lXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-16T02:41:39Z"
    mac: ENC[AES256_GCM,data:ChGBmoWJddUAp09Ty4mb7145f3s9uPavkOo7ZJO8IhSYnbRsUg3lcbwzvATBrsS+fO1K/puEtk2I9ZWyQIgYQ0LDx8y+oggviMlM5IfxIcgjk1V/yDes4124M3yEwpmMTqkADpD68axahRot9ZafCdJ7ckKZA5yD3iR49Cltlu4=,iv:PHKnji2oRPIdsUC7jjaQcnr54f9Nr//glIlyYysZr0E=,tag:aJukNujNf9Q2YCHp/iNU8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
