apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera-cluster-v11-3
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: password
  database: mariadb
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-secret
    key: password

  image: "mariadb:11.4.2"
  imagePullPolicy: IfNotPresent
  port: 3306

  # nodeSelector:
  #   kubernetes.io/arch: amd64

  env:
    - name: TZ
      value: ${TZ}

  replicas: 3

  galera:
    enabled: true
    primary:
      podIndex: 0
      automaticFailover: true
    sst: mariabackup
    replicaThreads: 1
    agent:
      image: ghcr.io/mariadb-operator/agent:v0.0.3
      #pullPolicy: IfNotPresent
      port: 5555
      kubernetesAuth:
        enabled: true
      gracefulShutdownTimeout: 5s
    recovery:
      enabled: true
      clusterHealthyTimeout: 3m
      clusterBootstrapTimeout: 10m
      podRecoveryTimeout: 5m
      podSyncTimeout: 5m
    initContainer:
      image: ghcr.io/mariadb-operator/init:v0.0.6
      #pullPolicy: IfNotPresent
    config:
      reuseStorageVolume: false
      volumeClaimTemplate:
        # storageClassName: ceph-block
        resources:
          requests:
            storage: 300Mi
        accessModes:
          - ReadWriteOnce

  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "mysql-lb.${SECRET_DOMAIN}"

  primaryService:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "mysql.${SECRET_DOMAIN}"

  secondaryService:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "mysql-ro.${SECRET_DOMAIN}"
    #secondaryConnection:
    #  secretName: mariadb-galera-conn-secondary
    #  secretTemplate:
    #    key: dsn

  storage:
    size: 5Gi
    storageClassName: ceph-block
    resizeInUseVolumes: true
    waitForVolumeResize: true
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: ceph-block

  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      memory: 2Gi

  # For Galera, Specifically
  podSecurityContext:
    runAsUser: 0

  securityContext:
    allowPrivilegeEscalation: false

  #podSecurityContext:
  #  runAsUser: 568
  #  runAsGroup: 568
  #  fsGroup: 568
  #  fsGroupChangePolicy: OnRootMismatch

  #service:
  #  type: LoadBalancer
  #  annotations:
  #    io.cilium/lb-ipam-ips: "${IPAM_MARIADB}"


  affinity:
    #nodeAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: database.mysql
    #          operator: In
    #          values:
    #            - "yes"
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"

  tolerations:
    - key: "mariadb.mmontes.io/ha"
      operator: "Exists"
      effect: "NoSchedule"

  podDisruptionBudget:
    maxUnavailable: 66%

  updateStrategy:
    type: RollingUpdate

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
    read_buffer_size=0
#    max_threads=10
