---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: lldap-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_LDAP_BASE_DN: "{{ .LLDAP_LDAP_BASE_DN }}"
        LLDAP_USER_DN: "{{ .LLDAP_USER_DN }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        LLDAP_DATABASE_URL: "postgres://{{ .LLDAP_POSTGRES_USER }}:{{ .LLDAP_POSTGRES_PASS }}@postgres-v16-rw.database.svc.cluster.local/lldap"
        # Postgres Init
        INIT_POSTGRES_DBNAME: "{{ .LLDAP_POSTGRES_DATABASE }}"
        INIT_POSTGRES_HOST: postgres-v16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .LLDAP_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .LLDAP_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lldap
    - extract:
        key: postgres
