---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kimai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: kimai-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Database
        host-db: &dbHost mariadb-galera-cluster-v11-3.database.svc.cluster.local
        name-db: &dbName "{{ .MYSQL_DB }}"
        username-db: &dbUser "{{ .MYSQL_USER }}"
        password-db: &dbPass "{{ .MYSQL_PASS }}"
        # aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        # aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
        # App
        app-secret: "{{ .APP_SECRET }}"
        admin-password: "{{ .ADMIN_PASS }}"
        # mailer-url: "{{ .MAILER_URL }}"
        mailer-url: "null://localhost"
        # database-url: "{{ .DB_URL }}"
        database-url: "mysql://{{ .MYSQL_USER }}:{{ .MYSQL_PASS }}@mariadb-galera-cluster-v11-3.database.svc.cluster.local/{{ .MYSQL_DB }}"
  dataFrom:
    - extract:
        key: kimai
