---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kimai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: kimai-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # username-db: "{{ .MYSQL_USER }}"
        password-db: "{{ .MYSQL_PASS }}"
        # aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        # aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: kimai
