---
cleanPrometheusOperatorObjectNames: true
fullnameOverride: prometheus
coreDns:
  enabled: true

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: false # FIXME

kubeEtcd:
  enabled: true

kubelet:
  enabled: true
  serviceMonitor:
    metricRelabelings:
      - action: replace
        sourceLabels:
          - node
        targetLabel: instance

kubeProxy:
  enabled: false # FIXME

kubeScheduler:
  enabled: false # FIXME

kubeStateMetrics:
  enabled: true

prometheusOperator:
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 145M
  #   limits:
  #     cpu: 15m
  #     memory: 145M

  prometheusConfigReloader:
    # resources:
    #   requests:
    #     cpu: 11m
    #     memory: 24M
    #   limits:
    #     cpu: 11m
    #     memory: 24M

grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true

kube-state-metrics:
  fullnameOverride: kube-state-metrics
  # resources:
  #   requests:
  #     cpu: 15m
  #     memory: 145M
  #   limits:
  #     cpu: 15m
  #     memory: 145M

nodeExporter:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node

prometheus-node-exporter:
  fullnameOverride: node-exporter
  # resources:
  #   requests:
  #     cpu: 23m
  #     memory: 64M
  #   limits:
  #     memory: 64M
  tolerations:
    - effect: "NoExecute"
      operator: "Exists"
    - effect: "NoSchedule"
      operator: "Exists"
