apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:1J6IJ94=,iv:N8TLRap/CAjmPRlTBgR+lhY96paK78nInbOOWu2hSLk=,tag:wyaz9148Z1qMetDuEFJ3MQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:dMdE98c=,iv:Can4BHP/w2DipuI/9fZbAGDw4T3rn1aDKhGehf8Q6A8=,tag:iMOw5FIJaewKAncWjTjBBw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4qeKhxK8TwZ28A==,iv:7Grg4f8SwmcF/wDsa3yg2HgLIAC+murWro9veZvOfro=,tag:aDVTArQ7neDOEC8L9aQZjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSVNobkduS3Rlak5VNnB0
            OVZpMEYxOUU1UWdBQlRiNHdlMnJtQ0xjRzNrCm9EMEpudTlaOEVXN2pYaE5WZHor
            d0lCQk4wemRXVnZvU1RjcWt6eW5nbjgKLS0tIFNtcGZ6N1BNejhLcGk2RWdsM0VY
            YkNWSzVsbXdMbDBZUTJkQ1dibzN0YW8KC2533PuvOj0EXi0ZxsihlEQcx6c55MEC
            q+AJr5U0X7zC3YgASokZ0UHzKKwMnZfe3Wp+XVej3N65hkCIruJkZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T04:31:05Z"
    mac: ENC[AES256_GCM,data:qceBImH+DQcU67Dol03eZMDrmlsk4N+Zahg5HL9MKCwjECYW5hM7skXj0Beqq1Vf2tT1C1+Egv9E2G5QNT17u1dWmwF9nNF86Q4ZsUBU2RHqIXZmoVcW54cGEiBXhTuaGd3j8fV2Chvwd9bY3S6LOwfqEXZCkYMuiMXxSxHndns=,iv:m4UjENELuGnzTJt2u3vzk7lY8Egey5gNnPF/+5iGs4M=,tag:1myuLJrbBgebn7foB5IYDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
