---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-restic
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: recyclarr-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/recyclarr'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .MINIO_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_KEY }}'
  dataFrom:
    - extract:
        key: minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: recyclarr-backup
  namespace: media
spec:
  sourcePVC: config-recyclarr-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: recyclarr-restic-secret
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
