apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:eq0Jo1Cu0Pg0wg==,iv:o4Pl/HxddnrnpybVqZPr6EoQE9hHmrj/eg+2jGunCgU=,tag:Sqk8MzmYsT5/5rVkKlmqUQ==,type:str]
    PUBLIC_DOMAIN: ENC[AES256_GCM,data:W8Tq/Ot8rMMl,iv:rdvIwWB8N5ZDsrNLMtz2u2znfv47nOmJAhqgRtbXBjM=,tag:wW5TvdZN/t7McIIsADMt8g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:2ELPuyvDrg4R4/FxkpVsQZI=,iv:IwpKoO5q0F6doVBJvVJ3PWg+dnac4Bo6D18YB3N1K8o=,tag:09J6CrSOl4JA2y5B7K/JJA==,type:str]
    NAS_IP: ENC[AES256_GCM,data:6ymDPYzFLr9cjKc=,iv:2DP3u836ltNKZlxskabyg0QGv5q3uSxM4pToWE61sCY=,tag:R21nUqxm07fTdLAoE1BjUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OFhMWWxZL0xQQ21KM2xX
            MTJNZzhHbHRTR1NuSGNEZko5UnRrS05jbWkwCmN2T0hVNndKTDFUZjNvTlZCczNN
            TzVUYzIxUXdRY2IxdnNBVjNnR1VIeEUKLS0tIFJQZlZrZTg1YnRockwzaGRKTFRV
            OWwxdGVRVnJQOFMyTGtFcG03YllxVEUKdJSY2n6CLpAfhn3Rjb0FJiPJ6Lvud0Si
            Wzo63vMQC6IKlchNfNTq2Sbhsv8HVXNkj8pIQhkiKl6jl4R5Fda3wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T22:45:32Z"
    mac: ENC[AES256_GCM,data:QhrV4KIpYPmawcGlqkUKdC75SCPi4s0YzOsOjJre3hO6PtC1eHnXpoyChDJQfV/X7vp+HO5KEjTI0FpNY3LUNVW5jZHMS0e7QPiVKlfPEAT91iJ4WG5Iy9IgZCbjhvM0znMDzIWLV1rclZmTesFZ1S5nbMAgvurSDcnFM9IHAxM=,iv:hXs7zvAXfal22sHpxzlo3EQqUBGoJ392wjA0uxTgcPc=,tag:/Sr4Bn9bfdnKi00+2iuZUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
