---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "10.200.0.250"
  METALLB_LB_RANGE: "10.200.0.40-10.200.0.50"
  METALLB_K8S_GATEWAY_ADDR: "10.200.0.41"
  METALLB_INGRESS_ADDR: "10.200.0.40"
  LB_EMQX: 10.200.0.42
  LB_OMADA_CONTROLLER: 10.200.0.49
