---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/mariadb-operator/mariadb-operator
      tag: v0.0.33
      pullPolicy: IfNotPresent
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      certificate:
        certManager: true
      serviceMonitor:
        enabled: true
