---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-red
spec:
  interval: 31m
  chart:
    spec:
      chart: app-template
      version: 3.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      node-red:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/k8s-at-home/node-red
              tag: v3.0.2
            env:
              TZ: "{$TIMEZONE}"
            # resources:
            #   requests:
            #     cpu: 15m
            #     memory: 164M
            #   limits:
            #     cpu: 15m
            #     memory: 164M

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: node-red
        ports:
          http:
            port: 1880

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Node-Red"
          gethomepage.dev/description: "Low-code programming for event-driven applications"
          gethomepage.dev/group: "Home Automation"
          gethomepage.dev/icon: "node-red.svg"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: *app
