---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      # data:
      #   username: "{{ .username }}"
      #   password: "{{ .password }}"
      #   aws-access-key-id: "{{ .aws-access-key-id }}"
      #   aws-secret-access-key: "{{ .aws-secret-access-key }}"
      # metadata:
      #   labels:
      #     cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudnative-pg
        property: aws-access-key-id
    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudnative-pg
        property: aws-secret-access-key
