---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        username: |-
          {{ .username }}
        password: |-
          {{ .password }}
        # db_url: |-
        #   postgresql://{{ .username }}:{{ .password }}@my-postgresql:5432/mydb
      # engineVersion: v2
      # metadata:
      #   labels:
      #     cnpg.io/reload: "true"
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  data:
    - secretKey: username
      # sourceRef:
      #   storeRef:
      #     name: bitwarden-fields
      #     kind: ClusterSecretStore
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
