---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: mariadb-operator
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      version: "0.22.0"

  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      repository: ghcr.io/mariadb-operator/mariadb-operator
      pullPolicy: IfNotPresent
      tag: v0.0.20
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      certificate:
        certManager: true
      serviceMonitor:
        enabled: true
