---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./galera-cluster-v11.3.yaml
  - ./scheduledbackup.yaml
