---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # controller:
    #   type: statefulset
    #   annotations:
    #     reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.4.5@sha256:fb84afb21e9d03b054934388cfbfeb24221dc2c9ad0771e320232fab1bf18691

    env:
      TZ: ${TIMEZONE}

    # envFrom:
    #   - secretRef:
    #       name: *app

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
          hajimari.io/targetBlank: "true"
        hosts:
          - host: &host "hass.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host

    # podSecurityContext:
    #   runAsUser: 568
    #   runAsGroup: 568
    #   fsGroup: 568
    #   fsGroupChangePolicy: "OnRootMismatch"
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: "OnRootMismatch"

    # persistence:
    #   config:
    #     enabled: true
    #     existingClaim: home-assistant-config-v2

    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: ceph-block

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.10.1
        env:
          TZ: "${TZ}"
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/icon: "microsoft-visual-studio-code"
            hajimari.io/targetBlank: "true"
          hosts:
            - host: &host "hass-code.${SECRET_INTERNAL_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          # tls:
          #   - hosts:
          #       - *host
        volumeMounts:
          - name: config
            mountPath: /config

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    # resources:
    #   requests:
    #     cpu: 48m
    #     memory: 443M
    #   limits:
    #     memory: 709M
