---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config-v2
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
