# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-restic-secret
    namespace: home-automation
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jKJu9JshkTwsboc6oD9b3Ks8l/1aaIHJQY+F6lSswOUmR1NQL/eQW8pOs/M2p3Fx+09OAjSpaw==,iv:1ed9fH3AQWZf63M8bdgc/DYPgc/ZSutb1cRFPPCL1N0=,tag:LD1awas4Qdk24MFtxichxQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:ncSKQFM=,iv:oas8TJE4hC6dObRw4kWsGdwYZ9GfMEur4NxpMAKRfaU=,tag:ENMeK7QyQMhpXGib2dkPVA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pXICSjmaUos48mDDRYsdhsV/k0I=,iv:gzUKBvp+McoPHz06fjHUrMwM+PvkH7ahE+gqQBNh6ec=,tag:yM1Y50m4ZWIMcQ1Y4h5bLw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PgLGinO7PiMA4tkz73EfMy/pz6pi0pza0JQDZjj/XJuqB8faVBw6Gw==,iv:n+PRK7PFIB6SoHnMjGmoH/veasqmFvOopOhJBZ4sPjM=,tag:eVIhLCLa+u4lkIAeRdDvoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upk6wpfn9hfmkpz2sxfe60pgkrkzvk2jrk7r4daszcyh474cffesnmfxl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHalZZU01VdlFIZUxHTk9h
            ZTZENWx6NlRxcDlqWS9wTjJlNGtwejVjdzBNCkM5d2lOZGtEcGpJbUw2MFczNjFG
            RWtYYXVVRnJuVVFDbXI5K3lmeHV5TTgKLS0tIGZXcUFFcWhYR0VOdWsyRzE1cFQw
            RTEvWVF5N0dkdmxYeVQrOWZFVmZhUVUKQteNJPJwV7Z4Ysz9NIOU7FupKjB0jAlD
            ZpG7KYmvBJ08sJN5oD31HBfLcRqa9hQzWqhsrpumM14YgGeBfBIw2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-27T14:17:19Z"
    mac: ENC[AES256_GCM,data:Dnd/JrKEeOkZeiTmEmoxX5Vtf2m8n8Iz8Rv4tFTXtBxG3GWfTo/3pj6mwRNfxszs5amMuyifaOhr7t9Z1jKSTS8HfHz4truQShB0fzUQ6gg5nhwIyjB4jGaiv/1G9Ouk80/x3uC1XOYjWaWUyrR1FqNxHFd8OnEBU4FlKNKlon0=,iv:/z4RinXjV0x6jGkLADZp+6A8QjfXjXhUj6OzNPc9Yzc=,tag:UFKD5wVRyWimnigQ4I5ZEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
