---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.31.0
    existingObjstoreSecret: &secret thanos-objstore-secret

    query:
      enabled: true
      replicaLabels:
        - replica

      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 15m
          memory: 64M

      ingress:
        # main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "archive-clock"
          hajimari.io/targetBlank: "true"
        hostname: "thanos-cluster.${SECRET_INTERNAL_DOMAIN}"
        # hosts:
        #   - host: "thanos-cluster.${SECRET_INTERNAL_DOMAIN}"

    queryFrontend:
      enabled: false

    bucketweb:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

      resources:
        # requests:
        #   cpu: 15m
        #   memory: 64M
        # limits:
        #   cpu: 15m
        #   memory: 64M

    compactor:
      enabled: true
      persistence:
        enabled: false
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

      resources:
        # requests:
        #   cpu: 35m
        #   memory: 110M
        # limits:
        #   cpu: 35m
        #   memory: 110M

    storegateway:
      enabled: true
      persistence:
        enabled: true
        storageClass: nfs-client
        size: 5Gi
      podAnnotations:
        configmap.reloader.stakater.com/reload: *secret

      # resources:
      #   requests:
      #     cpu: 35m
      #     memory: 204M
      #   limits:
      #     cpu: 35m
      #     memory: 204M

    ruler:
      enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
