---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: thanos
      version: 12.9.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.31.0
    existingObjstoreSecret: &secret thanos-objstore-secret

    query:
      enabled: true
      replicaLabels:
        - replica

      dnsDiscovery:
        sidecarsService: prometheus-thanos-discovery
        sidecarsNamespace: monitoring

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 26m
          memory: 189M

      ingress:
        # main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "archive-clock"
          hajimari.io/targetBlank: "true"
        hostname: "thanos-cluster.${SECRET_DOMAIN}"
        # hosts:
        #   - host: "thanos-cluster.${SECRET_INTERNAL_DOMAIN}"

    queryFrontend:
      enabled: true
      replicas: 1
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/targetBlank: "true"
        hostname: "thanos-query-frontend.${SECRET_DOMAIN}"

      resources:
        requests:
          cpu: 15m
          memory: 94M
        limits:
          cpu: 26m
          memory: 226M

    bucketweb:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

      resources:
        requests:
          cpu: 15m
          memory: 26M
        limits:
          cpu: 26m
          memory: 88M

    compactor:
      enabled: true
      persistence:
        enabled: false
      podAnnotations:
        secret.reloader.stakater.com/reload: *secret

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 26m
          memory: 306M

    storegateway:
      enabled: true
      persistence:
        enabled: true
        storageClass: ceph-block
        size: 20Gi
      podAnnotations:
        configmap.reloader.stakater.com/reload: *secret

      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 55m
          memory: 153M

    ruler:
      enabled: false

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
