---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: homepage-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        HOMEPAGE_VAR_GITLAB_URL: "{{ .HOMEPAGE_VAR_GITLAB_URL }}"
        HOMEPAGE_VAR_OMADA_USERNAME: "{{ .HOMEPAGE_VAR_OMADA_USERNAME }}"
        HOMEPAGE_VAR_OMADA_PASSWORD: "{{ .HOMEPAGE_VAR_OMADA_PASSWORD }}"
        HOMEPAGE_VAR_OMADA_SITE: "{{ .HOMEPAGE_VAR_OMADA_SITE }}"
        HOMEPAGE_VAR_PORTAINER_URL: "{{ .HOMEPAGE_VAR_PORTAINER_URL }}"
        HOMEPAGE_VAR_PORTAINER_TOKEN: "{{ .HOMEPAGE_VAR_PORTAINER_TOKEN }}"
        HOMEPAGE_VAR_HASS_URL: "{{ .HOMEPAGE_VAR_HASS_URL }}"
        HOMEPAGE_VAR_HASS_TOKEN: "{{ .HOMEPAGE_VAR_HASS_TOKEN }}"
        HOMEPAGE_VAR_LATITUDE: "{{ .HOMEPAGE_VAR_LATITUDE }}"
        HOMEPAGE_VAR_LONGITUDE: "{{ .HOMEPAGE_VAR_LONGITUDE }}"

  dataFrom:
    - extract:
        key: homepage
