---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v0.9.11
            env:
              # TZ: {$TIMEZONE}
              LOG_LEVEL: debug
            envFrom:
              - secretRef:
                  name: homepage-secret
            # resources:
            #   requests:
            #     cpu: 15m
            #     memory: 200M
            #   limits:
            #     memory: 2G

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: nginx
        annotations:
          hajimari.io/group: "Apps"
          # hajimari.io/enable: "false"
          # Example annotations to add Homepage to your Homepage!
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/name: "Homepage"
          # gethomepage.dev/description: "Dynamically Detected Homepage"
          # gethomepage.dev/group: "Dynamic"
          # gethomepage.dev/icon: "homepage.png"
        hosts:
          - host: &host "www.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: *app
