---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app netboot-xyz
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: lscr.io/linuxserver/netbootxyz
              tag: 0.7.1
            env:
              TZ: ${TIMEZONE}
              # MENU_VERSION: 2.0.75 #optional, unset pulls latest

            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 250Mi
            #   limits:
            #     # cpu: 476m
            #     memory: 2000Mi

    service:
      main:
        type: LoadBalancer
        # externalTrafficPolicy: Local
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: ${LB_NETBOOTXYZ}

        ports:
          http:
            port: 80
          webapp:
            enabled: true
            port: &port 3000
          tftp:
            enabled: true
            port: 69
            protocol: UDP

    # probes:
    #   liveness: &probes
    #     enabled: false
    #     custom: true
    #     spec:
    #       httpGet:
    #         path: /ping
    #         port: *port
    #       initialDelaySeconds: 0
    #       periodSeconds: 10
    #       timeoutSeconds: 1
    #       failureThreshold: 3
    #   readiness: *probes
    #   startup:
    #     enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: webapp
                  port: *port

    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /config
      assets:
        enabled: true
        existingClaim: netboot-pvc
        globalMounts:
          - path: /assets
