---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.8.7

    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/
      services:
        - My First Group:
            - My First Service:
                href: http://localhost/
                description: Homepage is awesome

        - My Second Group:
            - My Second Service:
                href: http://localhost/
                description: Homepage is the best

        - My Third Group:
            - My Third Service:
                href: http://localhost/
                description: Homepage is 😎
      widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - search:
            provider: duckduckgo
            target: _blank
        # - Sabnzbd:
        #     icon: "sabnzbd.svg"
        #     href: sabnzbd.${SECRET_DOMAIN}
        #     widget:
        #       type: sabnzbd
        #       url: sabnzbd.${SECRET_DOMAIN}
        #       key: apikeyapikeyapikeyapikeyapikey
      kubernetes:
        mode: cluster
      settings:
        theme: dark # or light
        color: neutral
        background:
          image: https://images.unsplash.com/photo-1652188820014-803f19447040?auto=format&fit=crop&w=2560&q=80
          blur: sm
          saturate: 50
          brightness: 50
          opacity: 50

    # The service account is necessary to allow discovery of other services
    serviceAccount:
      create: true
      name: homepage

    # This enables the service account to access the necessary resources
    enableRbac: true

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/group: "Apps"
          # hajimari.io/enable: "false"
          # Example annotations to add Homepage to your Homepage!
          # gethomepage.dev/enabled: "true"
          # gethomepage.dev/name: "Homepage"
          # gethomepage.dev/description: "Dynamically Detected Homepage"
          # gethomepage.dev/group: "Dynamic"
          # gethomepage.dev/icon: "homepage.png"
        hosts:
          - host: &host "www.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
          - host: "${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
