---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: authelia-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .LLDAP_LDAP_USER_PASS }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: "{{ .LLDAP_LDAP_BASE_DN }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_GROUPS_DN: "{{ .LLDAP_GROUP_DN }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDITIONAL_USERS_DN: "{{ .LLDAP_USER_DN }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "{{ .LLDAP_ADMIN_USER }},{{ .LLDAP_USER_DN }},{{ .LLDAP_LDAP_BASE_DN }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY }}"
        AUTHELIA_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_HOST: &dbHost postgres-rw.database.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbName "{{ .AUTHELIA_STORAGE_POSTGRES_DATABASE }}"
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbUser "{{ .AUTHELIA_STORAGE_POSTGRES_USERNAME }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbPass "{{ .AUTHELIA_STORAGE_POSTGRES_PASSWORD }}"
        AUTHELIA_NOTIFIER_SMTP_HOST: "{{ .AUTHELIA_SMTP_HOST }}"
        AUTHELIA_NOTIFIER_SMTP_PORT: "{{ .AUTHELIA_SMTP_PORT }}"
        AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .AUTHELIA_SMTP_USER }}"
        AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: "{{ .AUTHELIA_SMTP_PASS }}"
        AUTHELIA_NOTIFIER_SMTP_SENDER: "{{ .AUTHELIA_SMTP_SENDER }}"
        GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        # IMMICH_OAUTH_CLIENT_SECRET: "{{ .IMMICH_OAUTH_CLIENT_SECRET }}"
        # MINIFLUX_OAUTH_CLIENT_SECRET: "{{ .MINIFLUX_OAUTH_CLIENT_SECRET }}"
        # WEAVEGITOPS_OAUTH_CLIENT_SECRET: "{{ .WEAVEGITOPS_OAUTH_CLIENT_SECRET }}"
        # GITEA_OAUTH_CLIENT_SECRET: "{{ .GITEA_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: lldap
    - extract:
        key: authelia
    - extract:
        key: cloudnative-pg
