---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: vpa
      version: 2.5.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    recommender:
      enabled: true

      image:
        tag: 0.12.0

      resources:
        requests:
          cpu: 15m
          memory: 127M
        limits:
          cpu: 15m
          memory: 135M

      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        prometheus-address: |-
          http://thanos-query.monitoring.svc.cluster.local:9090
    updater:
      enabled: false

    admissionController:
      enabled: false
