---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_HOST: &dbHost postgres-v16-rw.database.svc.cluster.local
        POSTGRES_DB: &dbName "{{ .POSTGRES_DB }}"
        HASS_POSTGRES_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-v16-rw.database.svc.cluster.local/{{ .POSTGRES_DB }}"
        HASS_LATITUDE: "{{ .HASS_LATITUDE }}"
        HASS_LONGITUDE: "{{ .HASS_LONGITUDE }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: home-assistant
    - extract:
        key: postgres
