---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config-v1
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
