---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr
  namespace: media
spec:
  sourcePVC: config-lidarr-0
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: lidarr-restic-secret
    cacheCapacity: 1Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 7
      within: 3d
