---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/home-automation/zigbee2mqtt/app
  dependsOn:
    - name: emqx
    - name: rook-ceph-cluster
    - name: volsync
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app zigbee2mqtt-vscode
#   namespace: flux-system
#   labels:
#     substitution.flux.home.arpa/enabled: "true"
# spec:
#   targetNamespace: home-automation
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   path: ./kubernetes/apps/home-automation/zigbee2mqtt/vscode
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   healthChecks:
#     - apiVersion: helm.toolkit.fluxcd.io/v2beta1
#       kind: HelmRelease
#       name: *app
#       namespace: home-automation
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
