---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-red-vscode
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      node-red-code:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.89.1
            env:
              TZ: "{$TIMEZONE}"
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/data/.vscode"
              - --extensions-dir
              - "/data/.vscode"
              - "--port"
              - "80"
              - /config
            # resources:
            #   requests:
            #     cpu: 48m
            #     memory: 443M
            #   limits:
            #     memory: 709M

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

    service:
      app:
        controller: node-red-code
        ports:
          http:
            port: 80

    ingress:
      app:
        enabled: true
        className: nginx
        hosts:
          - host: &host "node-red-code.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        enabled: true
        existingClaim: node-red
