---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      resources:
        requests:
          cpu: 30m
          memory: 128M
        limits:
          cpu: 120m
          memory: 256M

    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 15m
          memory: 64M

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: ruler

        hosts:
          - host: &host "goldilocks.${SECRET_DOMAIN}"
            paths:
              - path: /
                type: Prefix

        # tls:
        #   - hosts:
        #     - *host
