---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: goldilocks
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controller:
      resources:
        requests:
          cpu: 48m
          memory: 79M
        limits:
          cpu: 117m
          memory: 189M

    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 26m
          memory: 64M

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: ruler

        hosts:
          - host: &host "goldilocks.${SECRET_INTERNAL_DOMAIN}"
            paths:
              - path: /
                type: Prefix

        # tls:
        #   - hosts:
        #     - *host
