---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: zigbee-controller
  namespace: monitoring
spec:
  staticConfigs:
    - targets: ["zigbee-controller.turbo.ac"]
  metricsPath: /metrics
